---
- name: Install nfs-common
  apt:
    name: nfs-common
    state: present

- name: Create mount point directory
  file:
    path: "{{ efs_mount_point }}"
    state: directory
    mode: '0755'

- name: Mount EFS
  mount:
    path: "{{ efs_mount_point }}"
    src: "{{ hostvars['localhost']['efs_dns_name'] }}:/"
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
    state: mounted

- name: Set permissions on EFS mount point
  file:
    path: "{{ efs_mount_point }}"
    owner: "33"
    group: "33"
    mode: '0775'
    state: directory
